### ISSUE TITLE
small detail - US census results "Exact" vs "Match"

### ISSUE THREAD

**Issue by JackDougherty** [ilyankou/geocoder-for-google-sheets#1]
this is a very small detail, but when running the US Census geocoder, the first result usually appears as "Exact" but other results appear as "Match"
![leaflet_maps_with_google_sheets_development_-_google_sheets](https://cloud.githubusercontent.com/assets/649719/23340817/ba819454-fc0a-11e6-89fd-311790cfd396.png)

**Comment by ilyankou** [comment]
Yes, if you remember, our 'Exact' estimate is very basic. It takes the address, removes all spaces and syntax, lowercases the string and compares it to the 'Found Address'. If you notice, the first row has 'St', whereas all other rows have 'Street'. Thus, it only shows 'Match' and not 'Exact'.

I tried to come up with a solution to compare the addresses, but it requires bulky functions and it will never work 100% correctly. Even if I allow 'St' to be interpreted as 'Street', there will be plenty of other cases where match won't be 'Exact' for the exact same addresses.
