### ISSUE TITLE
how to interpret bad Mapzen geocoding results

### ISSUE THREAD

**Issue by JackDougherty** [ilyankou/geocoder-for-google-sheets#3]
It appears that Mapzen geocoding results are not very good, in comparison to US Census and Google.

We can't fix Mapzen, but we need to decide how to tell users to interpret Mapzen results.

I ran Mapzen (with API key) and found that 6 out of 14 were bad results. See screenshot with red X symbols. But there's no correspondence with the numerical results in the Match Quality column. 
![leaflet_maps_with_google_sheets_development_-_google_sheets](https://cloud.githubusercontent.com/assets/649719/23340912/8b9e3dfc-fc0c-11e6-9522-773f00352bc3.png)

By comparison, US Census was perfect (7 for 7) with US addresses, but no match for non-US.
Also, Google did very well with 13 out of 14 correct results (including 1 correct "no match" for an imaginary address), but 1 incorrect result (by arbitrarily placing 100 Main St in White Plains NY)

**Comment by ilyankou** [comment]
Mapzen works with 4 different services: OpenAddresses (used now), OpenStreetMap, Who's On First, and GeoNames.

https://mapzen.com/documentation/search/data-sources/

If you open Geocoder script and go to line 157, you can change the geocoding source and see who gives the best results.
